
package org.superbiz.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-04-28T10:02:35.622+02:00
 * Generated source version: 2.6.13
 * 
 */
public final class CalculatorWs_CalculatorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://superbiz.org/wsdl", "CalculatorService");

    private CalculatorWs_CalculatorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculatorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalculatorService ss = new CalculatorService(wsdlURL, SERVICE_NAME);
        CalculatorWs port = ss.getCalculatorPort();  
        
        {
        System.out.println("Invoking sum...");
        int _sum_arg0 = -2035605302;
        int _sum_arg1 = 1872003512;
        int _sum__return = port.sum(_sum_arg0, _sum_arg1);
        System.out.println("sum.result=" + _sum__return);


        }
        {
        System.out.println("Invoking multiply...");
        int _multiply_arg0 = 1823486632;
        int _multiply_arg1 = -59177830;
        int _multiply__return = port.multiply(_multiply_arg0, _multiply_arg1);
        System.out.println("multiply.result=" + _multiply__return);


        }

        System.exit(0);
    }

}
