
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.superbiz.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.13
 * 2014-04-28T10:02:35.680+02:00
 * Generated source version: 2.6.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalculatorService",
                      portName = "CalculatorPort",
                      targetNamespace = "http://superbiz.org/wsdl",
                      wsdlLocation = "http://localhost:9080/RouterWebProject/CalculatorService/CalculatorService.wsdl",
                      endpointInterface = "org.superbiz.wsdl.CalculatorWs")
                      
public class CalculatorWsImpl implements CalculatorWs {

    private static final Logger LOG = Logger.getLogger(CalculatorWsImpl.class.getName());

    /* (non-Javadoc)
     * @see org.superbiz.wsdl.CalculatorWs#sum(int  arg0 ,)int  arg1 )*
     */
    public int sum(int arg0,int arg1) { 
        LOG.info("Executing operation sum");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1294008726;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.superbiz.wsdl.CalculatorWs#multiply(int  arg0 ,)int  arg1 )*
     */
    public int multiply(int arg0,int arg1) { 
        LOG.info("Executing operation multiply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -715322976;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
